# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: conf.py  # Ensure this path is correct relative to the root of your repo

python:
  install:
    - requirements: docs/requirements.txt  # Ensure this file exists

# Specify the correct branch for cloning if needed
versions:
  only:
    - gh-pages
